ci_service: travis_ci
coverage_service: coveralls
workspace: ContactsWrapper.xcodeworkspace
xcodeproj: ContactsWrapper.xcodeproj
scheme: ContactsWrapper
source_directory: ContactsWrapper/Source
ignore:
  - ContactsWrapper/Sample/AppDelegate.h
  - ContactsWrapper/Sample/AppDelegate.m
  - ContactsWrapper/Sample/ContactsTableViewController.h
  - ContactsWrapper/Sample/ContactsTableViewController.m
  - ContactsWrapper/Sample/Supporting Files/main.m
# output_directory: code_coverage/xml_report