language: objective-c
osx_image: xcode7.3
xcode_project: ContactsWrapper.xcworkspace
xcode_scheme: ContactsWrapperTests
xcode_sdk: iphonesimulator9.0
sudo: required

branches:
 only:
 - master

before_install:
- rm -rf /Users/travis/Library/Developer/Xcode/DerivedData/ContactsWrapper-*/
- rvm use $RVM_RUBY_VERSION

install: bundle

script: 
- xcodebuild -workspace ContactsWrapper.xcworkspace -scheme ContactsWrapper -destination "platform=iOS Simulator,name=iPhone 6,OS=9.1" clean test GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES

after_success: slather