language: objective-c
osx_image: xcode7.3
xcode_project: ContactsWrapper.xcworkspace
xcode_scheme: ContactsWrapperTests
xcode_sdk: iphonesimulator9.0
sudo: required

branches:
 only:
 - master

before_install:
- rm -rf /Users/travis/Library/Developer/Xcode/DerivedData/
- gem install slather


script: 
- xcodebuild -workspace ContactsWrapper.xcworkspace -scheme ContactsWrapper -destination "platform=iOS Simulator,name=iPhone 6,OS=9.1" clean test GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
# xctool -workspace 'ContactsWrapper.xcworkspace' -scheme 'ContactsWrapper' -sdk 'iphonesimulator' -configuration Debug clean test

after_success: slather coverage -s --scheme ContactsWrapper --workspace ContactsWrapper.xcworkspace ContactsWrapper.xcodeproj